# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second Page.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Screen2(object):
    def setupUi(self, Screen2):
        Screen2.setObjectName("Screen2")
        Screen2.resize(713, 499)
        self.centralwidget = QtWidgets.QWidget(Screen2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 120, 451, 181))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 390, 93, 28))
        self.pushButton.setObjectName("pushButton")
        Screen2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Screen2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 26))
        self.menubar.setObjectName("menubar")
        Screen2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Screen2)
        self.statusbar.setObjectName("statusbar")
        Screen2.setStatusBar(self.statusbar)

        self.retranslateUi(Screen2)
        QtCore.QMetaObject.connectSlotsByName(Screen2)

    def retranslateUi(self, Screen2):
        _translate = QtCore.QCoreApplication.translate
        Screen2.setWindowTitle(_translate("Screen2", "second  Page"))
        self.label.setText(_translate("Screen2", "Welcome to second page"))
        self.pushButton.setText(_translate("Screen2", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Screen2 = QtWidgets.QMainWindow()
    ui = Ui_Screen2()
    ui.setupUi(Screen2)
    Screen2.show()
    sys.exit(app.exec_())
